/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banksystemprototype.accounts.TermDepositAccount;

import banksystemprototype.TypeOfAccountAction;
import banksystemprototype.TypeOfMessageDialog;
import banksystemprototype.accounts.CustomerHomeFrame;
import banksystemprototype.accounts.Database.DBConnection;
import static java.lang.System.in;
import java.sql.Connection;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Iterator;
import java.util.List;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SpinnerListModel;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author caidong
 */
public class TermDepositAccountFrame extends javax.swing.JFrame implements TermDepositAccountContract.View{

    /**
     * Creates new form SavingAccountFrame
     */
    private final CustomerHomeFrame homeFrame;
    private List<TermDeposit> mTempTerms;
    private final TermDepositAccountContract.UserActionListener mActionListener;
    private String[] mOptionValues;
    public TermDepositAccountFrame(JFrame home) {
        initComponents();
        homeFrame = (CustomerHomeFrame) home;
        mActionListener = new TermDepositAccountController(this);
        mActionListener.openAccount(homeFrame.getUsername());
        dateChooserTermDeposit.setMinDate(Calendar.getInstance());
        spTermPeriod.addChangeListener(spinnerTermPeriodListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfTransferAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spTransferTermDeposit = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        tfCreateTermDepositAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        spTermPeriod = new javax.swing.JSpinner();
        dateChooserTermDeposit = new datechooser.beans.DateChooserCombo();
        jLabel11 = new javax.swing.JLabel();
        labelInterestRate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spWithdrawTermDeposit = new javax.swing.JSpinner();
        tfWithdrawAmount = new javax.swing.JTextField();
        dialogViewTermDeposits = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        btnViewTermDeposits = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelBalanceValue = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        dialogTransfer.setTitle("Withdraw");
        dialogTransfer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                dialogTransferComponentHidden(evt);
            }
        });

        jLabel2.setText("Amount:");

        tfTransferAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTransferAmountActionPerformed(evt);
            }
        });

        btnTransferOK.setText("OK");
        btnTransferOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferOKActionPerformed(evt);
            }
        });

        btnTransferCancel.setText("Cancel");
        btnTransferCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferCancelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Transfer Money");

        jLabel8.setText("To Account:");

        tfTransferToAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTransferToAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogTransferLayout = new javax.swing.GroupLayout(dialogTransfer.getContentPane());
        dialogTransfer.getContentPane().setLayout(dialogTransferLayout);
        dialogTransferLayout.setHorizontalGroup(
            dialogTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTransferLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(dialogTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogTransferLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnTransferOK)
                        .addGap(31, 31, 31)
                        .addComponent(btnTransferCancel))
                    .addGroup(dialogTransferLayout.createSequentialGroup()
                        .addGroup(dialogTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(dialogTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogTransferLayout.createSequentialGroup()
                                .addComponent(tfTransferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spTransferTermDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfTransferToAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        dialogTransferLayout.setVerticalGroup(
            dialogTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTransferLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTransferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(spTransferTermDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTransferToAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(dialogTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransferOK)
                    .addComponent(btnTransferCancel))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        dialogCreateTermDeposit.setTitle("Create Term Deposit");
        dialogCreateTermDeposit.setMinimumSize(new java.awt.Dimension(300, 470));
        dialogCreateTermDeposit.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                dialogCreateTermDepositComponentHidden(evt);
            }
        });

        jLabel4.setText("Amount:");

        tfCreateTermDepositAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCreateTermDepositAmountActionPerformed(evt);
            }
        });

        btnCreateTermDepositOK.setText("OK");
        btnCreateTermDepositOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTermDepositOKActionPerformed(evt);
            }
        });

        btnCreateTermDepositCancel.setText("Cancel");
        btnCreateTermDepositCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTermDepositCancelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Create Term Deposit");

        jLabel9.setText("Starting Date:");

        jLabel10.setText("Term Period:");

        spTermPeriod.setModel(new javax.swing.SpinnerListModel(new String[] {"3 Months", "6 Months", "12 Months"}));

        jLabel11.setText("Interest Rate: ");

        labelInterestRate.setText("3%");

        javax.swing.GroupLayout dialogCreateTermDepositLayout = new javax.swing.GroupLayout(dialogCreateTermDeposit.getContentPane());
        dialogCreateTermDeposit.getContentPane().setLayout(dialogCreateTermDepositLayout);
        dialogCreateTermDepositLayout.setHorizontalGroup(
            dialogCreateTermDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCreateTermDepositLayout.createSequentialGroup()
                .addGroup(dialogCreateTermDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogCreateTermDepositLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(dialogCreateTermDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(dialogCreateTermDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCreateTermDepositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spTermPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserTermDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelInterestRate)))
                    .addGroup(dialogCreateTermDepositLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel5))
                    .addGroup(dialogCreateTermDepositLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnCreateTermDepositOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateTermDepositCancel)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        dialogCreateTermDepositLayout.setVerticalGroup(
            dialogCreateTermDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCreateTermDepositLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogCreateTermDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfCreateTermDepositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogCreateTermDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(dateChooserTermDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogCreateTermDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTermPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogCreateTermDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelInterestRate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(dialogCreateTermDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateTermDepositOK)
                    .addComponent(btnCreateTermDepositCancel))
                .addGap(16, 16, 16))
        );

        dialogWithdraw.setTitle("Transfer");
        dialogWithdraw.setMinimumSize(getPreferredSize());
        dialogWithdraw.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                dialogWithdrawComponentHidden(evt);
            }
        });

        jLabel6.setText("Amount");

        btnWithdrawOK.setText("OK");
        btnWithdrawOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawOKActionPerformed(evt);
            }
        });

        btnWithdrawCancel.setText("Cancel");
        btnWithdrawCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawCancelActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Withdraw Money");

        spWithdrawTermDeposit.setModel(new javax.swing.SpinnerListModel(new String[] {""}));

        tfWithdrawAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWithdrawAmountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogWithdrawLayout = new javax.swing.GroupLayout(dialogWithdraw.getContentPane());
        dialogWithdraw.getContentPane().setLayout(dialogWithdrawLayout);
        dialogWithdrawLayout.setHorizontalGroup(
            dialogWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogWithdrawLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(152, 152, 152))
            .addGroup(dialogWithdrawLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogWithdrawLayout.createSequentialGroup()
                        .addComponent(tfWithdrawAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogWithdrawLayout.createSequentialGroup()
                        .addComponent(btnWithdrawOK)
                        .addGap(37, 37, 37)))
                .addGroup(dialogWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWithdrawCancel)
                    .addComponent(spWithdrawTermDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        dialogWithdrawLayout.setVerticalGroup(
            dialogWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogWithdrawLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(dialogWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spWithdrawTermDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWithdrawAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdrawOK)
                    .addComponent(btnWithdrawCancel))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        dialogViewTermDeposits.setTitle("Term Deposits");

        javax.swing.GroupLayout dialogViewTermDepositsLayout = new javax.swing.GroupLayout(dialogViewTermDeposits.getContentPane());
        dialogViewTermDeposits.getContentPane().setLayout(dialogViewTermDepositsLayout);
        dialogViewTermDepositsLayout.setHorizontalGroup(
            dialogViewTermDepositsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogViewTermDepositsLayout.setVerticalGroup(
            dialogViewTermDepositsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnCreateTermDeposit.setText("Create Term Deposit");
        btnCreateTermDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTermDepositActionPerformed(evt);
            }
        });

        btnTransfer.setText("Transfer");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        btnViewTermDeposits.setText("View Term Deposit");
        btnViewTermDeposits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTermDepositsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateTermDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewTermDeposits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateTermDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewTermDeposits, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Balance:");

        labelBalanceValue.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelBalanceValue.setText("number");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelBalanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBack)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelBalanceValue))
                .addGap(102, 102, 102)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateTermDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTermDepositActionPerformed
        // TODO add your handling code here:
        dialogCreateTermDeposit.setVisible(true);
    }//GEN-LAST:event_btnCreateTermDepositActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        // TODO add your handling code here:
        mActionListener.showTermDeposits(TypeOfAccountAction.WITHDRAW);
        dialogWithdraw.setVisible(true);
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        // TODO add your handling code here:
        mActionListener.showTermDeposits(TypeOfAccountAction.TRANSFER);
        dialogTransfer.setVisible(true);
       
    }//GEN-LAST:event_btnTransferActionPerformed

    private void tfTransferAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTransferAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTransferAmountActionPerformed

    private void tfTransferToAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTransferToAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTransferToAccountActionPerformed

    private void dialogTransferComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dialogTransferComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_dialogTransferComponentHidden

    private void tfCreateTermDepositAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCreateTermDepositAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCreateTermDepositAmountActionPerformed

    private void dialogCreateTermDepositComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dialogCreateTermDepositComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_dialogCreateTermDepositComponentHidden

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        mActionListener.back();
        this.dispose();
        homeFrame.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTransferOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferOKActionPerformed
        // TODO add your handling code here:
        mActionListener.newAction(TypeOfAccountAction.TRANSFER);
    }//GEN-LAST:event_btnTransferOKActionPerformed

    private void btnCreateTermDepositOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTermDepositOKActionPerformed
        // TODO add your handling code here:
        mActionListener.newAction(TypeOfAccountAction.CREATE_DEPOSIT);
    }//GEN-LAST:event_btnCreateTermDepositOKActionPerformed

    private void btnCreateTermDepositCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTermDepositCancelActionPerformed
        // TODO add your handling code here:
        disposeActionDialog(TypeOfAccountAction.CREATE_DEPOSIT);
    }//GEN-LAST:event_btnCreateTermDepositCancelActionPerformed

    private void btnTransferCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferCancelActionPerformed
        // TODO add your handling code here:
        disposeActionDialog(TypeOfAccountAction.TRANSFER);
    }//GEN-LAST:event_btnTransferCancelActionPerformed

    private void btnViewTermDepositsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTermDepositsActionPerformed
        // TODO add your handling code here:
        dialogViewTermDeposits.setVisible(true);
    }//GEN-LAST:event_btnViewTermDepositsActionPerformed

    private void dialogWithdrawComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dialogWithdrawComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_dialogWithdrawComponentHidden

    private void btnWithdrawCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawCancelActionPerformed
        // TODO add your handling code here:
        disposeActionDialog(TypeOfAccountAction.WITHDRAW);
    }//GEN-LAST:event_btnWithdrawCancelActionPerformed

    private void btnWithdrawOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawOKActionPerformed
        // TODO add your handling code here:
        mActionListener.newAction(TypeOfAccountAction.WITHDRAW);
    }//GEN-LAST:event_btnWithdrawOKActionPerformed

    private void tfWithdrawAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWithdrawAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWithdrawAmountActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private final javax.swing.JButton btnCreateTermDeposit = new javax.swing.JButton();
    private final javax.swing.JButton btnCreateTermDepositCancel = new javax.swing.JButton();
    private final javax.swing.JButton btnCreateTermDepositOK = new javax.swing.JButton();
    private final javax.swing.JButton btnTransfer = new javax.swing.JButton();
    private final javax.swing.JButton btnTransferCancel = new javax.swing.JButton();
    private final javax.swing.JButton btnTransferOK = new javax.swing.JButton();
    private javax.swing.JButton btnViewTermDeposits;
    private final javax.swing.JButton btnWithdraw = new javax.swing.JButton();
    private final javax.swing.JButton btnWithdrawCancel = new javax.swing.JButton();
    private final javax.swing.JButton btnWithdrawOK = new javax.swing.JButton();
    private datechooser.beans.DateChooserCombo dateChooserTermDeposit;
    private final javax.swing.JDialog dialogCreateTermDeposit = new javax.swing.JDialog();
    private final javax.swing.JDialog dialogTransfer = new javax.swing.JDialog();
    private javax.swing.JDialog dialogViewTermDeposits;
    private final javax.swing.JDialog dialogWithdraw = new javax.swing.JDialog();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelBalanceValue;
    private javax.swing.JLabel labelInterestRate;
    private javax.swing.JSpinner spTermPeriod;
    private javax.swing.JSpinner spTransferTermDeposit;
    private javax.swing.JSpinner spWithdrawTermDeposit;
    private javax.swing.JTextField tfCreateTermDepositAmount;
    private javax.swing.JTextField tfTransferAmount;
    private final javax.swing.JTextField tfTransferToAccount = new javax.swing.JTextField();
    private javax.swing.JTextField tfWithdrawAmount;
    // End of variables declaration//GEN-END:variables

    @Override
    public double getTransferAmount() {
        return Double.parseDouble(tfTransferAmount.getText());
    }

    @Override
    public long getTransferAccountId() {
        return Long.parseLong(tfTransferToAccount.getText());
    }

    @Override
    public double getWithdrawAmount() {
        return Double.parseDouble(tfWithdrawAmount.getText());
    }

    @Override
    public double getCreateDepositAmount() {
        return Double.valueOf(tfCreateTermDepositAmount.getText());
    }

    @Override
    public TypeOfTermDeposit getTypeOfTermDeposit() {
        String term = spTermPeriod.getValue().toString();
        switch((term).toLowerCase()) {
            case "3 months":
                return TypeOfTermDeposit.THREE_MONTHS;
            case "6 months":
                return TypeOfTermDeposit.SIX_MONTHS;
            case "12 months":
                return TypeOfTermDeposit.TWELVE_MONTHS;
        }
        return null;
    }

    @Override
    public Date getTermDepositStartingDate() {
        Date selectedDate = dateChooserTermDeposit.getSelectedDate().getTime();
        return selectedDate;
    }

    @Override
    public long getTransferTermDepositId() {
        return getSelectedTermId(spTransferTermDeposit);
    }

    @Override
    public long getWithdrawTermDepositId() {
        return getSelectedTermId(spWithdrawTermDeposit);
    }

    @Override
    public void disposeActionDialog(TypeOfAccountAction action) {
        switch(action) {
            case CREATE_DEPOSIT:
                dialogCreateTermDeposit.setVisible(false);
                tfCreateTermDepositAmount.setText("");
                break;
            case WITHDRAW:
                dialogWithdraw.setVisible(false);
                tfWithdrawAmount.setText("");
                break;
            case TRANSFER:
                dialogTransfer.setVisible(false);
                tfTransferAmount.setText("");
                tfTransferToAccount.setText("");
                break;
            default:
                break;
        }
    }

    @Override
    public void showMessageDialog(String msg,  TypeOfMessageDialog type) {
         switch(type) {
            case WARNING: 
                JOptionPane.showMessageDialog(this, msg, type.toString(), JOptionPane.WARNING_MESSAGE);
                break;
            case PLAIN:
                JOptionPane.showMessageDialog(this, msg, type.toString(), JOptionPane.PLAIN_MESSAGE);
                break;
            case ERROR:
                JOptionPane.showMessageDialog(this, msg, type.toString(), JOptionPane.ERROR_MESSAGE);

        }
    }

    @Override
    public void showTermDeposit(HashMap<Long, TermDeposit> terms, TypeOfAccountAction action) {
        mTempTerms = new ArrayList<>();
        String[] options = new String[terms.size()];
        int i = 0;
        Iterator it = terms.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry pair = (Map.Entry)it.next();
            String amount = new DecimalFormat("#0.00").format((((TermDeposit) pair.getValue()).getTotalAccrueAmount(new Date())));
            options[i] = "Term" + (i+1) + ": " + amount;
            mTempTerms.add((TermDeposit) pair.getValue());
            i++;
        }
        mOptionValues = options;
        
        if(options.length == 0) return;
        SpinnerModel model = new SpinnerListModel(options);
        switch(action) {
            case WITHDRAW:
                spWithdrawTermDeposit.setModel(model);
                spWithdrawTermDeposit.addChangeListener(spinnerWithdrawListener);
                break;
            case TRANSFER:
                spTransferTermDeposit.setModel(model);
                spTransferTermDeposit.addChangeListener(spinnerTransferListener);
        }
        
    }
    
    private final ChangeListener spinnerWithdrawListener = new  ChangeListener() {
        @Override
        public void stateChanged(ChangeEvent e) {
          String value = spWithdrawTermDeposit.getValue().toString();
            Pattern p = Pattern.compile(" (\\d+.*\\d*)");
            Matcher m = p.matcher(value);
            if(m.find()) {
                String amount = new StringBuilder(m.group(1)).toString().trim();
                tfWithdrawAmount.setText(amount);
            }        
//            TermDeposit term = getSelectedTerm(spWithdrawTermDeposit);
//            tfWithdrawAmount.setText(String.valueOf(term.getTotalAccrueAmount(new Date())));
        }
    };
    
     private final ChangeListener spinnerTransferListener = new  ChangeListener() {
        @Override
        public void stateChanged(ChangeEvent e) {
            String value = spTransferTermDeposit.getValue().toString();
            Pattern p = Pattern.compile(" ([\\d]+.*[\\d]*)");
            Matcher m = p.matcher(value);
            if(m.find()) {
                String amount = new StringBuilder(m.group(1)).toString().trim();
                tfTransferAmount.setText(amount);
            }    
//            TermDeposit term = getSelectedTerm(spTransferTermDeposit);
//            tfTransferAmount.setText(String.valueOf(term.getTotalAccrueAmount(new Date())));
        }
    };
     
    private final ChangeListener spinnerTermPeriodListener = new ChangeListener() {
        @Override
        public void stateChanged(ChangeEvent e) {
            String value = spTermPeriod.getValue().toString();
            switch(value) {
                case "3 Months": 
                    labelInterestRate.setText("3%");
                    break;
                case "6 Months":
                    labelInterestRate.setText("4%");
                    break;
                case "12 Months":
                    labelInterestRate.setText("5%");
            }
        }
    };
    
     private int getSelectedIndex(javax.swing.JSpinner spinner, String[] values) {
        int index=0;
        for(String o :values) {
            if(o.equals(spinner.getValue()))
                return index;
            index++;
        }
        return -1;
     }
     
     private long getSelectedTermId(javax.swing.JSpinner spinner) {
        int index = getSelectedIndex(spinner, mOptionValues);
        return mTempTerms.get(index).getTermId();
     }
     
     private TermDeposit getSelectedTerm(javax.swing.JSpinner spinner) {
        int index = getSelectedIndex(spinner, mOptionValues);
        return mTempTerms.get(index);
     }
     

    @Override
    public void refreshBalance(String balance) {
        labelBalanceValue.setText(balance);
    }
}
