/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banksystemprototype.accounts;
import banksystemprototype.accounts.Database.*;

import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import banksystemprototype.users.LoginFrame;
import javax.swing.JFrame;

/**
 *
 * @author yanjunwu
 */
public class AdminHomeFrame extends javax.swing.JFrame {
    Connection conn = null;
    Statement stmt = null;
    ResultSetMetaData mdata;
    DefaultTableModel dtm = new DefaultTableModel(new String[]{
    "Account_id", "username", "account type", "lock_status", "balance"}, 0);
    DefaultComboBoxModel dcm = new DefaultComboBoxModel(); 
    DefaultTableModel dtmHomeLoan = new DefaultTableModel(new String[]{
    "loan_id", "Account_id", "Principal", "Interest", "Remain Loan", "$Repayment","interest_rate","period","start_date","end_date","repayment_date","next_repayment_date","finish_status"}, 0);
    DefaultTableModel CreditTableModel = new DefaultTableModel(new String[]{
    "Account_id", "daily_payment_limit", "loan_limit"}, 0);
    private LoginFrame loginFrame;
    private String username;
    
    public AdminHomeFrame(JFrame login, String username) {
        initComponents();
        conn = DBConnection.getConnection();
        loginFrame = (LoginFrame) login;
        this.username = username;
        labelUsername.setText(username);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdCreateCustomer = new javax.swing.JDialog();
        cbCreateIDType = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfCreateUsername = new javax.swing.JTextField();
        tfCreateFname = new javax.swing.JTextField();
        tfCreateLname = new javax.swing.JTextField();
        tfCreateEmail = new javax.swing.JTextField();
        tfCreateAddress = new javax.swing.JTextField();
        tfCreatePhone = new javax.swing.JTextField();
        tfCreateIDNo = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pfCreatePassword = new javax.swing.JPasswordField();
        pfCreatePin = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jOptionPane1 = new javax.swing.JOptionPane();
        jdAdminAccountManage = new javax.swing.JDialog();
        btnViewAllAccount = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        tfSearchUsername = new javax.swing.JTextField();
        btnSearchAccountByCustomer = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCreateAccount = new javax.swing.JButton();
        btnUnlockAccount = new javax.swing.JButton();
        btnModifyCreditLimit = new javax.swing.JButton();
        jdChangePin = new javax.swing.JDialog();
        tfInputUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pfResetPin = new javax.swing.JPasswordField();
        btnSubmitPinReset = new javax.swing.JButton();
        btnCancelResetPin = new javax.swing.JButton();
        jdHomeLoan = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHomeLoan = new javax.swing.JTable();
        btnViewHomeLoanApplication = new javax.swing.JButton();
        btnCreateHomeLoan = new javax.swing.JButton();
        btnBackHomepage = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfHomeLoanUsername = new javax.swing.JTextField();
        tfPrincipal = new javax.swing.JTextField();
        tfMonthlyRepayment = new javax.swing.JTextField();
        tfInterestRate = new javax.swing.JTextField();
        tfPeriod = new javax.swing.JTextField();
        tfStartDate = new javax.swing.JTextField();
        tfEndDate = new javax.swing.JTextField();
        tfRepaymentDate = new javax.swing.JTextField();
        jdCreateAccount = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbAccountType = new javax.swing.JComboBox<>();
        btnSubmitCreateAccount = new javax.swing.JButton();
        btnCancelCreateAccount = new javax.swing.JButton();
        jdUnlockAccount = new javax.swing.JDialog();
        btnSubmitUnlock = new javax.swing.JButton();
        btnCancelUnlock = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tfAccountID = new javax.swing.JTextField();
        jdModifyCreditLimit = new javax.swing.JDialog();
        jLabel27 = new javax.swing.JLabel();
        tfCreditAccountID = new javax.swing.JTextField();
        tfCreditLimit = new javax.swing.JTextField();
        btnSubmitCreditLimitChange = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnViewCreditAccount = new javax.swing.JButton();
        cbCreditLimitType = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnTermDepositAccount = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();

        jdCreateCustomer.setMinimumSize(new java.awt.Dimension(466, 550));
        jdCreateCustomer.setSize(getPreferredSize());

        cbCreateIDType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passport", "Driver License", "ID card" }));
        cbCreateIDType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCreateIDTypeActionPerformed(evt);
            }
        });

        jLabel15.setText("last name");

        jLabel10.setText("ID type");

        jLabel4.setText("email");

        jLabel5.setText("phone number");

        jLabel11.setText("ID Number");

        jLabel12.setText("first name");

        jLabel8.setText("Username");

        jLabel9.setText("Password");

        jLabel6.setText("address");

        jLabel7.setText("PIN");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        pfCreatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfCreatePasswordActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextField1.setText("Create Customer");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdCreateCustomerLayout = new javax.swing.GroupLayout(jdCreateCustomer.getContentPane());
        jdCreateCustomer.getContentPane().setLayout(jdCreateCustomerLayout);
        jdCreateCustomerLayout.setHorizontalGroup(
            jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdCreateCustomerLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCreateCustomerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addGroup(jdCreateCustomerLayout.createSequentialGroup()
                            .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel11)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9))
                            .addGap(12, 12, 12))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdCreateCustomerLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel8)))
                    .addGroup(jdCreateCustomerLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnSubmit)))
                .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCreateCustomerLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCreateUsername)
                            .addComponent(tfCreateFname)
                            .addComponent(tfCreateLname)
                            .addComponent(tfCreateEmail)
                            .addComponent(tfCreateAddress)
                            .addComponent(tfCreatePhone)
                            .addComponent(tfCreateIDNo)
                            .addComponent(cbCreateIDType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pfCreatePassword)
                            .addComponent(pfCreatePin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdCreateCustomerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)))
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdCreateCustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jdCreateCustomerLayout.setVerticalGroup(
            jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdCreateCustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCreateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pfCreatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCreateFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCreateCustomerLayout.createSequentialGroup()
                        .addComponent(tfCreateLname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfCreateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfCreateAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfCreatePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCreateIDType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(tfCreateIDNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pfCreatePin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdCreateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel))
                .addGap(40, 40, 40))
        );

        btnViewAllAccount.setText("View All Customer Accounts");
        btnViewAllAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllAccountActionPerformed(evt);
            }
        });

        jTable1.setModel(dtm);
        jScrollPane1.setViewportView(jTable1);

        jLabel14.setText("Enter Customer Username:");

        btnSearchAccountByCustomer.setText("Search Accounts by customer");
        btnSearchAccountByCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAccountByCustomerActionPerformed(evt);
            }
        });

        btnBack.setText("Back To Home Page");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreateAccount.setText("Create Customer Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        btnUnlockAccount.setText("Unlock Account");
        btnUnlockAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnlockAccountActionPerformed(evt);
            }
        });

        btnModifyCreditLimit.setText("Modify Credit Account limit");
        btnModifyCreditLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyCreditLimitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdAdminAccountManageLayout = new javax.swing.GroupLayout(jdAdminAccountManage.getContentPane());
        jdAdminAccountManage.getContentPane().setLayout(jdAdminAccountManageLayout);
        jdAdminAccountManageLayout.setHorizontalGroup(
            jdAdminAccountManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAdminAccountManageLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jdAdminAccountManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdAdminAccountManageLayout.createSequentialGroup()
                        .addGroup(jdAdminAccountManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewAllAccount)
                            .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jdAdminAccountManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnUnlockAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModifyCreditLimit, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jdAdminAccountManageLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnSearchAccountByCustomer)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jdAdminAccountManageLayout.setVerticalGroup(
            jdAdminAccountManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdAdminAccountManageLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jdAdminAccountManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchAccountByCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAdminAccountManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAllAccount)
                    .addComponent(btnUnlockAccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAdminAccountManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAccount)
                    .addComponent(btnModifyCreditLimit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(14, 14, 14))
        );

        jdChangePin.setMinimumSize(getPreferredSize());

        jLabel3.setText("Input Customer username:");

        jLabel13.setText("Reset pin:");

        pfResetPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfResetPinActionPerformed(evt);
            }
        });

        btnSubmitPinReset.setText("Submit");
        btnSubmitPinReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPinResetActionPerformed(evt);
            }
        });

        btnCancelResetPin.setText("Cancel");
        btnCancelResetPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelResetPinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdChangePinLayout = new javax.swing.GroupLayout(jdChangePin.getContentPane());
        jdChangePin.getContentPane().setLayout(jdChangePinLayout);
        jdChangePinLayout.setHorizontalGroup(
            jdChangePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdChangePinLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jdChangePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jdChangePinLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jdChangePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubmitPinReset)
                            .addComponent(jLabel13))))
                .addGap(26, 26, 26)
                .addGroup(jdChangePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdChangePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfInputUsername)
                        .addComponent(pfResetPin, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancelResetPin))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jdChangePinLayout.setVerticalGroup(
            jdChangePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdChangePinLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jdChangePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfInputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jdChangePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pfResetPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jdChangePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitPinReset)
                    .addComponent(btnCancelResetPin))
                .addGap(17, 17, 17))
        );

        jdHomeLoan.setMinimumSize(new java.awt.Dimension(1400, 550));

        /*
        DefaultTableModel dtmHomeLoan = new DefaultTableModel(new String[]{
            "Application_no", "username", "Amount", "Period", "Start_date", "End_Date"}, 0);
    */
    tblHomeLoan.setModel(dtmHomeLoan);
    jScrollPane2.setViewportView(tblHomeLoan);

    btnViewHomeLoanApplication.setText("View All Home Loan");
    btnViewHomeLoanApplication.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnViewHomeLoanApplicationActionPerformed(evt);
        }
    });

    btnCreateHomeLoan.setText("Create Home Loan");
    btnCreateHomeLoan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCreateHomeLoanActionPerformed(evt);
        }
    });

    btnBackHomepage.setText("Back To Home Page");
    btnBackHomepage.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBackHomepageActionPerformed(evt);
        }
    });

    jLabel19.setText("Username");

    jLabel20.setText("Principal");

    jLabel22.setText("Monthly Repayment ");

    jLabel23.setText("Interest rate");

    jLabel21.setText("Period");

    jLabel24.setText("Start date");

    jLabel25.setText("End date");

    jLabel26.setText("Monthly Repay date");

    tfHomeLoanUsername.setText(" ");

    tfPrincipal.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tfPrincipalActionPerformed(evt);
        }
    });

    tfStartDate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tfStartDateActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jdHomeLoanLayout = new javax.swing.GroupLayout(jdHomeLoan.getContentPane());
    jdHomeLoan.getContentPane().setLayout(jdHomeLoanLayout);
    jdHomeLoanLayout.setHorizontalGroup(
        jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jdHomeLoanLayout.createSequentialGroup()
            .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jdHomeLoanLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
                .addGroup(jdHomeLoanLayout.createSequentialGroup()
                    .addGap(237, 237, 237)
                    .addComponent(btnViewHomeLoanApplication)))
            .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdHomeLoanLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(btnBackHomepage)
                    .addGap(25, 25, 25))
                .addGroup(jdHomeLoanLayout.createSequentialGroup()
                    .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jdHomeLoanLayout.createSequentialGroup()
                            .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel19)
                                .addComponent(jLabel23)
                                .addComponent(jLabel22)
                                .addComponent(jLabel21)
                                .addComponent(jLabel24)
                                .addComponent(jLabel25)
                                .addComponent(jLabel26))
                            .addGap(18, 18, 18)
                            .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfHomeLoanUsername)
                                .addComponent(tfPrincipal)
                                .addComponent(tfMonthlyRepayment)
                                .addComponent(tfInterestRate)
                                .addComponent(tfPeriod)
                                .addComponent(tfStartDate)
                                .addComponent(tfEndDate)
                                .addComponent(tfRepaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jdHomeLoanLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCreateHomeLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18))))
    );
    jdHomeLoanLayout.setVerticalGroup(
        jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdHomeLoanLayout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jdHomeLoanLayout.createSequentialGroup()
                    .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(tfHomeLoanUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(tfPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(tfMonthlyRepayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(tfInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(tfPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(tfStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(tfEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(tfRepaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(btnCreateHomeLoan)
                    .addGap(14, 14, 14))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jdHomeLoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnBackHomepage)
                .addComponent(btnViewHomeLoanApplication))
            .addContainerGap(26, Short.MAX_VALUE))
    );

    jLabel16.setText("Username:");

    jLabel17.setText("Account Type:");

    cbAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SAVING", "TERM_DEPOSIT", "LOAN", "CREDIT" }));

    btnSubmitCreateAccount.setText("Submit");
    btnSubmitCreateAccount.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSubmitCreateAccountActionPerformed(evt);
        }
    });

    btnCancelCreateAccount.setText("Cancel");
    btnCancelCreateAccount.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelCreateAccountActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jdCreateAccountLayout = new javax.swing.GroupLayout(jdCreateAccount.getContentPane());
    jdCreateAccount.getContentPane().setLayout(jdCreateAccountLayout);
    jdCreateAccountLayout.setHorizontalGroup(
        jdCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jdCreateAccountLayout.createSequentialGroup()
            .addGap(74, 74, 74)
            .addGroup(jdCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(btnSubmitCreateAccount)
                .addComponent(jLabel17)
                .addComponent(jLabel16))
            .addGap(49, 49, 49)
            .addGroup(jdCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jdCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfUsername)
                    .addComponent(cbAccountType, 0, 117, Short.MAX_VALUE))
                .addComponent(btnCancelCreateAccount))
            .addContainerGap(83, Short.MAX_VALUE))
    );
    jdCreateAccountLayout.setVerticalGroup(
        jdCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jdCreateAccountLayout.createSequentialGroup()
            .addGap(63, 63, 63)
            .addGroup(jdCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel16)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jdCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17)
                .addComponent(cbAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(68, 68, 68)
            .addGroup(jdCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSubmitCreateAccount)
                .addComponent(btnCancelCreateAccount))
            .addContainerGap(42, Short.MAX_VALUE))
    );

    jdUnlockAccount.setMinimumSize(getPreferredSize());

    btnSubmitUnlock.setText("Unlock");
    btnSubmitUnlock.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSubmitUnlockActionPerformed(evt);
        }
    });

    btnCancelUnlock.setText("Cancel");
    btnCancelUnlock.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelUnlockActionPerformed(evt);
        }
    });

    jLabel18.setText("Account ID");

    javax.swing.GroupLayout jdUnlockAccountLayout = new javax.swing.GroupLayout(jdUnlockAccount.getContentPane());
    jdUnlockAccount.getContentPane().setLayout(jdUnlockAccountLayout);
    jdUnlockAccountLayout.setHorizontalGroup(
        jdUnlockAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jdUnlockAccountLayout.createSequentialGroup()
            .addGap(51, 51, 51)
            .addGroup(jdUnlockAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(btnSubmitUnlock)
                .addComponent(jLabel18))
            .addGroup(jdUnlockAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jdUnlockAccountLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(tfAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(96, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdUnlockAccountLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelUnlock)
                    .addGap(71, 71, 71))))
    );
    jdUnlockAccountLayout.setVerticalGroup(
        jdUnlockAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdUnlockAccountLayout.createSequentialGroup()
            .addGap(63, 63, 63)
            .addGroup(jdUnlockAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18)
                .addComponent(tfAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(26, 26, 26)
            .addGroup(jdUnlockAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSubmitUnlock)
                .addComponent(btnCancelUnlock))
            .addContainerGap(98, Short.MAX_VALUE))
    );

    jLabel27.setText("Credit Account ID");

    tfCreditAccountID.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tfCreditAccountIDActionPerformed(evt);
        }
    });

    tfCreditLimit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tfCreditLimitActionPerformed(evt);
        }
    });

    btnSubmitCreditLimitChange.setText("Submit");
    btnSubmitCreditLimitChange.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSubmitCreditLimitChangeActionPerformed(evt);
        }
    });

    Cancel.setText("Cancel");
    Cancel.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            CancelActionPerformed(evt);
        }
    });

    jTable2.setModel(CreditTableModel);
    jScrollPane3.setViewportView(jTable2);
    DefaultTableModel CreditTableModel = new DefaultTableModel(new String[]{
        "Account_id", "username", "account type", "lock_status", "balance"}, 0);

btnViewCreditAccount.setText("View Credit Card Status");
btnViewCreditAccount.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnViewCreditAccountActionPerformed(evt);
    }
    });

    cbCreditLimitType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "daily_payment_limit", "loan_limit" }));

    javax.swing.GroupLayout jdModifyCreditLimitLayout = new javax.swing.GroupLayout(jdModifyCreditLimit.getContentPane());
    jdModifyCreditLimit.getContentPane().setLayout(jdModifyCreditLimitLayout);
    jdModifyCreditLimitLayout.setHorizontalGroup(
        jdModifyCreditLimitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jdModifyCreditLimitLayout.createSequentialGroup()
            .addGroup(jdModifyCreditLimitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jdModifyCreditLimitLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnViewCreditAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdModifyCreditLimitLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(jdModifyCreditLimitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jdModifyCreditLimitLayout.createSequentialGroup()
                            .addComponent(btnSubmitCreditLimitChange)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cancel))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdModifyCreditLimitLayout.createSequentialGroup()
                            .addComponent(cbCreditLimitType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCreditLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jdModifyCreditLimitLayout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCreditAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addContainerGap(53, Short.MAX_VALUE))
    );
    jdModifyCreditLimitLayout.setVerticalGroup(
        jdModifyCreditLimitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdModifyCreditLimitLayout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addGroup(jdModifyCreditLimitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel27)
                .addComponent(tfCreditAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnViewCreditAccount)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jdModifyCreditLimitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfCreditLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cbCreditLimitType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jdModifyCreditLimitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSubmitCreditLimitChange)
                .addComponent(Cancel))
            .addGap(30, 30, 30))
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    btnTermDepositAccount.setText("Home Loan Approval");
    btnTermDepositAccount.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTermDepositAccountActionPerformed(evt);
        }
    });

    btnChangePIN.setText("Change Customer PIN");
    btnChangePIN.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnChangePINActionPerformed(evt);
        }
    });

    btnCreateCustomer.setText("Create Customer ");
    btnCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCreateCustomerActionPerformed(evt);
        }
    });

    btnHomeLoanAccount.setText("Customer Account Management");
    btnHomeLoanAccount.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnHomeLoanAccountActionPerformed(evt);
        }
    });

    jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
    jLabel1.setText("Welcome Back");

    labelUsername.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
    labelUsername.setText("username");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jSeparator1))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(labelUsername)))
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(btnChangePIN, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addComponent(btnCreateCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(btnTermDepositAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHomeLoanAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(labelUsername)
            .addGap(51, 51, 51)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(btnCreateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnChangePIN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(btnTermDepositAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnHomeLoanAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btnViewProfile.setText("View Profile");
    btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnViewProfileActionPerformed(evt);
        }
    });

    btnLogOut.setText("Log out");
    btnLogOut.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLogOutActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(btnLogOut)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewProfile)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnViewProfile)
                .addComponent(btnLogOut))
            .addGap(18, 18, 18)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTableModel(DefaultTableModel dcbm){
        if (dcbm.getRowCount() > 0) {
            /* clear the default table model */
            for (int i = dcbm.getRowCount() - 1; i > -1; i--) {
                dcbm.removeRow(i);
            }
        }
    }
            
    private void btnTermDepositAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTermDepositAccountActionPerformed
        jdHomeLoan.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnTermDepositAccountActionPerformed

    private void btnChangePINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePINActionPerformed
        jdChangePin.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnChangePINActionPerformed

    private void btnCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCustomerActionPerformed
        jdCreateCustomer.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnCreateCustomerActionPerformed

    private void btnHomeLoanAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeLoanAccountActionPerformed
        jdAdminAccountManage.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnHomeLoanAccountActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void cbCreateIDTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCreateIDTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCreateIDTypeActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try 
        {
            String sql = "Insert into S27624366.Customers (username, password, fname, lname, email, address, phone, id_type, ID_no, pin) values (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, tfCreateUsername.getText());
            pst.setString(2, pfCreatePassword.getPassword().toString());
            pst.setString(3, tfCreateFname.getText());
            pst.setString(4, tfCreateLname.getText());
            pst.setString(5, tfCreateEmail.getText());
            pst.setString(6, tfCreateAddress.getText());
            Long phone = Long.parseLong(tfCreatePhone.getText());
            pst.setLong(7, phone);
            String id_type;
            id_type = cbCreateIDType.getSelectedItem().toString();
            pst.setString(8, id_type);
            pst.setString(9, tfCreateIDNo.getText());
            pst.setString(10,pfCreatePin.getPassword().toString());  
            pst.executeUpdate();
            jOptionPane1.showMessageDialog(null,"insert successfully!");
        }
        catch(SQLException ex)
        {
            jOptionPane1.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnViewAllAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllAccountActionPerformed
        addTableModel(dtm);
        String condition = "";
        String table = "S27624366.Accounts";
        ArrayList<Object[]> rows = DBManager.check(table, condition);
        for(Object[] row: rows) {
             dtm.addRow(row);
        }     
    }//GEN-LAST:event_btnViewAllAccountActionPerformed

    private void pfCreatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfCreatePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfCreatePasswordActionPerformed

    private void btnSubmitPinResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPinResetActionPerformed
        try 
        {
            String sql = "update S27624366.Customers set PIN = ? where username = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, pfResetPin.getPassword().toString());
            pst.setString(2, tfInputUsername.getText());
            pst.executeUpdate();
            jOptionPane1.showMessageDialog(null,"Pin has been reset successfully!");
        }
        catch(SQLException ex)
        {
            jOptionPane1.showMessageDialog(null,ex);
        }    
    }//GEN-LAST:event_btnSubmitPinResetActionPerformed

    private void pfResetPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfResetPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfResetPinActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnViewHomeLoanApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHomeLoanApplicationActionPerformed
        addTableModel(dtmHomeLoan);
        String condition = "";
        String table = "S27624366.home_loans";
        ArrayList<Object[]> rows = DBManager.check(table, condition);
        for(Object[] row: rows) {
             dtmHomeLoan.addRow(row);
        }     
    }//GEN-LAST:event_btnViewHomeLoanApplicationActionPerformed

    private void btnCreateHomeLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHomeLoanActionPerformed
//        try 
//        {
//            stmt = conn.createStatement();
//            String getAccountID = "select account_id from account where username = " + tfHomeLoanUsername.getText() + " And account_type ='LOAN'";
//            ResultSet rset = stmt.executeQuery(getAccountID);
//            mdata = rset.getMetaData();
//            String sql = "Insert into S27624366.Home_Loan (loanid_seq.nextval, Account_id,principal, interest, remain_loan, repayment_amount, interest_rate, period, start_date, end_date, repay_date, next_repay_date, finish_status) values (loanid_seq.nextval,?,?,0,?,?,?,?,?,?,?,null,'N')";
//            PreparedStatement pst = conn.prepareStatement(sql);
//            pst.setString(1, mdata.toString());
//            Long principal = Long.parseLong(tfPrincipal.getText());
//            pst.setLong(2, principal);
//            pst.setLong(3, principal);
//            Long repayment = Long.parseLong(tfMonthlyRepayment.getText());
//            pst.setLong(4, repayment);
//            Long interestRate = Long.parseLong(tfInterestRate.getText());
//            pst.setLong(5, interestRate);
//            Long period = Long.parseLong(tfPeriod.getText());
//            pst.setLong(6, period);
//            pst.setDate(7,java.sql.Date.valueOf(tfStartDate.getText());
//            pst.setDate(7, Date(tfStartDate.getTime());
//            pst.setDate(8, java.sql.Date.valueOf("tfEndDate.getText()"));
//            Long phone = Long.parseLong(tfCreatePhone.getText());
//            pst.setLong(7, phone);
//            String id_type;
//            id_type = cbCreateIDType.getSelectedItem().toString();
//            pst.setString(8, id_type);
//            pst.setString(9, tfCreateIDNo.getText());
//            pst.setString(10,pfCreatePin.getPassword().toString());  
//            pst.executeUpdate();
//            jOptionPane1.showMessageDialog(null,"Home Loan has been created!");
//        }
//        catch(SQLException ex)
//        {
//            jOptionPane1.showMessageDialog(null,ex);
//        }
    }//GEN-LAST:event_btnCreateHomeLoanActionPerformed

    private void btnBackHomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackHomepageActionPerformed
        jdHomeLoan.dispose();
        this.setEnabled(true);
    }//GEN-LAST:event_btnBackHomepageActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        jdCreateCustomer.dispose();
        this.setEnabled(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelResetPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelResetPinActionPerformed
        jdChangePin.dispose();
        this.setEnabled(true);
    }//GEN-LAST:event_btnCancelResetPinActionPerformed

    private void btnSearchAccountByCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAccountByCustomerActionPerformed
        addTableModel(dtm);
        String condition = " where username = '" + tfSearchUsername.getText() + "'";
        String table = "S27624366.Accounts";
        ArrayList<Object[]> rows = DBManager.check(table, condition);
        for(Object[] row: rows) {
             dtm.addRow(row);
        }    
    }//GEN-LAST:event_btnSearchAccountByCustomerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        jdAdminAccountManage.dispose();
        this.setEnabled(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        jdCreateAccount.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnCreateAccountActionPerformed
        
    private void btnSubmitCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitCreateAccountActionPerformed
        try 
        {
            stmt = conn.createStatement();
            /* insert a student record using the values from JTextField txtID and txtName */
            String checksql = "select account_type from S27624366.Account where username ='" + tfUsername.getText() + "'";
            stmt.executeUpdate(checksql);
            
            String sql = "Insert into S27624366.Accounts (account_id, username, account_type, lockstatus, balance) values (accountid_seq.nextval,?,?,'N',0)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, tfUsername.getText());
            String account_type = cbAccountType.getSelectedItem().toString();
            pst.setString(2, account_type);
            pst.executeUpdate();
            jOptionPane1.showMessageDialog(null,"Account has been created!");
        }
        catch(SQLException ex)
        {
            jOptionPane1.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_btnSubmitCreateAccountActionPerformed

    private void btnCancelCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelCreateAccountActionPerformed
        jdCreateAccount.dispose();
        this.setEnabled(true);
    }//GEN-LAST:event_btnCancelCreateAccountActionPerformed

    private void btnUnlockAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnlockAccountActionPerformed
        jdUnlockAccount.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnUnlockAccountActionPerformed

    private void btnSubmitUnlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitUnlockActionPerformed
        try 
        {
            String sql = "update S27624366.Accounts set lockstatus = 'N' where account_id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, tfAccountID.getText());
            pst.executeUpdate();
            jOptionPane1.showMessageDialog(null,"Account gets unlock successfully!");
        }
        catch(SQLException ex)
        {
            jOptionPane1.showMessageDialog(null,ex);
        }    
    }//GEN-LAST:event_btnSubmitUnlockActionPerformed

    private void btnCancelUnlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelUnlockActionPerformed
        jdUnlockAccount.dispose();
        this.setEnabled(true);
    }//GEN-LAST:event_btnCancelUnlockActionPerformed

    private void btnModifyCreditLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyCreditLimitActionPerformed
        jdModifyCreditLimit.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnModifyCreditLimitActionPerformed

    private void btnViewCreditAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCreditAccountActionPerformed
        addTableModel(CreditTableModel);
        String condition = " where account_id = " + tfCreditAccountID.getText();
        String table = "S27624366.Credit_Accounts";
        ArrayList<Object[]> rows = DBManager.check(table, condition);
        for(Object[] row: rows) {
             CreditTableModel.addRow(row);
        }    
    }//GEN-LAST:event_btnViewCreditAccountActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        jdModifyCreditLimit.dispose();
        this.setEnabled(true);
    }//GEN-LAST:event_CancelActionPerformed

    private void btnSubmitCreditLimitChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitCreditLimitChangeActionPerformed
          try 
        {
            String sql = "update S27624366.credit_accounts set " + cbCreditLimitType.getSelectedItem().toString() + " = ? where account_id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            Long creditLimit = Long.parseLong(tfCreditLimit.getText());
            pst.setLong(1, creditLimit);
            Long accountId = Long.parseLong(tfCreditAccountID.getText());
            pst.setLong(2, accountId);
            pst.executeUpdate();
            jOptionPane1.showMessageDialog(null,"Credit Card limit has been changed!");
        }
        catch(SQLException ex)
        {
            jOptionPane1.showMessageDialog(null,ex);
        }     
    }//GEN-LAST:event_btnSubmitCreditLimitChangeActionPerformed

    private void tfPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrincipalActionPerformed

    private void tfCreditLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCreditLimitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCreditLimitActionPerformed

    private void tfCreditAccountIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCreditAccountIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCreditAccountIDActionPerformed

    public void showLogout() {
        loginFrame.setVisible(true);
        this.dispose();
    }
    
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        this.dispose();
        showLogout();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void tfStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStartDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomeFrame(new LoginFrame(), "newAdmin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBackHomepage;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelCreateAccount;
    private javax.swing.JButton btnCancelResetPin;
    private javax.swing.JButton btnCancelUnlock;
    private final javax.swing.JButton btnChangePIN = new javax.swing.JButton();
    private javax.swing.JButton btnCreateAccount;
    private final javax.swing.JButton btnCreateCustomer = new javax.swing.JButton();
    private javax.swing.JButton btnCreateHomeLoan;
    private final javax.swing.JButton btnHomeLoanAccount = new javax.swing.JButton();
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnModifyCreditLimit;
    private javax.swing.JButton btnSearchAccountByCustomer;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmitCreateAccount;
    private javax.swing.JButton btnSubmitCreditLimitChange;
    private javax.swing.JButton btnSubmitPinReset;
    private javax.swing.JButton btnSubmitUnlock;
    private javax.swing.JButton btnTermDepositAccount;
    private javax.swing.JButton btnUnlockAccount;
    private javax.swing.JButton btnViewAllAccount;
    private javax.swing.JButton btnViewCreditAccount;
    private javax.swing.JButton btnViewHomeLoanApplication;
    private final javax.swing.JButton btnViewProfile = new javax.swing.JButton();
    private javax.swing.JComboBox<String> cbAccountType;
    private javax.swing.JComboBox<String> cbCreateIDType;
    private javax.swing.JComboBox<String> cbCreditLimitType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JDialog jdAdminAccountManage;
    private javax.swing.JDialog jdChangePin;
    private javax.swing.JDialog jdCreateAccount;
    private javax.swing.JDialog jdCreateCustomer;
    private javax.swing.JDialog jdHomeLoan;
    private javax.swing.JDialog jdModifyCreditLimit;
    private javax.swing.JDialog jdUnlockAccount;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPasswordField pfCreatePassword;
    private javax.swing.JPasswordField pfCreatePin;
    private javax.swing.JPasswordField pfResetPin;
    private javax.swing.JTable tblHomeLoan;
    private javax.swing.JTextField tfAccountID;
    private javax.swing.JTextField tfCreateAddress;
    private javax.swing.JTextField tfCreateEmail;
    private javax.swing.JTextField tfCreateFname;
    private javax.swing.JTextField tfCreateIDNo;
    private javax.swing.JTextField tfCreateLname;
    private javax.swing.JTextField tfCreatePhone;
    private javax.swing.JTextField tfCreateUsername;
    private javax.swing.JTextField tfCreditAccountID;
    private javax.swing.JTextField tfCreditLimit;
    private javax.swing.JTextField tfEndDate;
    private javax.swing.JTextField tfHomeLoanUsername;
    private javax.swing.JTextField tfInputUsername;
    private javax.swing.JTextField tfInterestRate;
    private javax.swing.JTextField tfMonthlyRepayment;
    private javax.swing.JTextField tfPeriod;
    private javax.swing.JTextField tfPrincipal;
    private javax.swing.JTextField tfRepaymentDate;
    private javax.swing.JTextField tfSearchUsername;
    private javax.swing.JTextField tfStartDate;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
